######################################################################
# Automatically generated by qmake (2.01a) Mi. Jun 19 16:37:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
