######################################################################
# Automatically generated by qmake (2.01a) Di. Jun 18 00:16:00 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
