git config --global user.name "Frank W. Rahn"
git config --global user.email "...@frank-rahn.de"
git config --global color.diff "auto"
git config --global color.status "auto"
git config --global color.branch "auto"
git config --global color.interactive "auto"
git config --global color.ui "true"
git config --global core.editor "vim"
git config --global merge.tool "vimdiff"
git config --global pack.threads "0"
