######################################################################
# Automatically generated by qmake (2.01a) Do. Jun 20 02:01:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += elements.h mywidget.h
SOURCES += elements.cpp main.cpp mywidget.cpp
